import assert from 'node:assert/strict';
import {applyEdit,at,diagramScene,layoutScene,freshVariables,insertionPath,variablesIn} from './graph.mjs';
const atom=(relation,...args)=>({kind:'atom',atom:{relation,args}});
const model={program:{rules:[{name:'r',kept:[{relation:'p',args:['V0']}],removed:[],body:{kind:'or',items:[atom('q','V1'),{kind:'equal',left:'V2',right:'X'}]}}]},query:{kind:'and',items:[atom('a','V0'),{kind:'and',items:[atom('b','V1'),{kind:'true'}]}]}};
const query=['query','items',0],rule=['program','rules',0,'body','items',0];
assert.deepEqual(freshVariables(model,query,2),['V2','V3']);
assert.deepEqual(freshVariables(model,rule,2),['V3','V4']);
const added=applyEdit(model,{type:'insert-port',path:rule});
assert.equal(at(added,rule).atom.args.at(-1),'V3');
assert.equal(variablesIn(model.program.rules[0]).includes('V3'),false);
assert.deepEqual(insertionPath(model,[...rule]),rule);
assert.deepEqual(insertionPath(model,['query','items',1,'items',0]),['query']);
assert.deepEqual(insertionPath(model,['program','rules',0,'kept',0]),['program','rules',0,'kept']);
const body=['program','rules',0,'body'];
const appended=applyEdit(model,{type:'append',path:body,node:atom('s','F')});
assert.equal(at(appended,body).kind,'and');
assert.deepEqual(at(appended,[...body,'items',0]),at(model,body));
const alternative=applyEdit(model,{type:'add-alternative',path:body});
assert.equal(at(alternative,body).items.length,3);
const eq=['program','rules',0,'body','items',1];
assert.equal(at(applyEdit(model,{type:'set-port',path:eq,index:1,variable:'V0'}),eq).right,'V0');
const empty={program:{rules:[]},query:{kind:'true'}};
assert.deepEqual(applyEdit(empty,{type:'append',path:['query'],node:atom('a','V0')}).query,atom('a','V0'));
const diagram=layoutScene(diagramScene(model,['query']));
assert.deepEqual(diagram.items.filter(i=>i.type==='node').map(i=>i.relation),['a','b']);
assert.deepEqual(diagram.items.filter(i=>i.type==='boundary').map(i=>i.label),['Query']);
const split=layoutScene(diagramScene(model,body));
assert.equal(split.items.filter(i=>i.type==='boundary'&&i.kind==='branch').length,2);
assert.ok(split.items.every(i=>i.label!=='And'));
console.log('Fresh connections, spatial insertion, empty compartments, alternatives and equality editing passed.');
