import assert from 'node:assert/strict';
import {diagramScene, layoutScene, visibleItems, applyEdit} from './graph.mjs';
const atom = (relation, ...args) => ({kind:'atom',atom:{relation,args}});
const model = {program:{rules:[{name:'rewrite',kept:[{relation:'keep',args:['X']}],removed:[{relation:'take',args:['X','Y']}],body:{kind:'or',items:[atom('left','Y','Z'),{kind:'and',items:[atom('right','X','Z'),{kind:'equal',left:'Y',right:'Z'}]}]}}]},query:{kind:'true'}};
const before = structuredClone(model);
const scene = diagramScene(model,['program','rules',0,'body']);
const layout = layoutScene(scene);
assert.deepEqual(model,before);
assert.deepEqual(layout.items.filter(n=>n.type==='boundary').map(n=>n.label).filter(n=>['Kept','Removed','Body','Or','And'].includes(n)),['Kept','Removed','Body','Or']);
assert.equal(layout.items.filter(n=>n.type==='node').length,5);
assert.equal(layout.items.find(n=>n.type==='node'&&n.kind==='equal').label,'=');

const disjunction=layout.items.find(n=>n.type==='boundary'&&n.kind==='or');
const sections=layout.items.filter(n=>n.type==='boundary'&&n.kind==='branch');
assert.ok(sections.every(s=>s.x===disjunction.x&&s.width===disjunction.width));
assert.equal(sections[0].y+sections[0].height,sections[1].y);
assert.equal(sections.at(-1).y+sections.at(-1).height,disjunction.y+disjunction.height);
const port=layout.items.find(n=>n.type==='port'&&n.relation==='right'&&n.port===1);
const edited=applyEdit(model,{type:'set-port',path:port.path,index:port.port,variable:'Y'});
assert.deepEqual(edited.program.rules[0].body.items[1].items[0].atom.args,['X','Y']);
assert.deepEqual(model,before);
const moved=layoutScene(scene,new Map([[JSON.stringify(port.path),{x:300,y:200}]]));
const movedNode=moved.items.find(n=>n.type==='node'&&n.relation==='right');
const alternative=moved.items.find(n=>n.type==='boundary'&&n.label==='Alternative 2');
assert.ok(movedNode.x+movedNode.width<=alternative.x+alternative.width);
assert.ok(movedNode.y+movedNode.height<=alternative.y+alternative.height);
for(const delta of [{x:300,y:200},{x:-100,y:-150}]) {
  const changed=layoutScene(scene,new Map([[JSON.stringify(port.path),delta]]));
  const box=changed.items.find(n=>n.type==='boundary'&&n.kind==='or');
  const parts=changed.items.filter(n=>n.type==='boundary'&&n.kind==='branch');
  assert.ok(parts.every(p=>p.x===box.x&&p.width===box.width));
  assert.equal(parts[0].y,box.y+38);
  assert.equal(parts[0].y+parts[0].height,parts[1].y);
  assert.equal(parts.at(-1).y+parts.at(-1).height,box.y+box.height);
}
const wide=layoutScene(diagramScene({query:atom('wide',...Array.from({length:30},(_,i)=>`V${i}`))},['query']));
assert.equal(wide.items.filter(n=>n.type==='port').length,30);
const large=layoutScene(diagramScene({query:{kind:'and',items:Array.from({length:2000},(_,i)=>atom('p',`V${i}`))}},['query']));
const window={x:0,y:0,width:800,height:500};
const shown=visibleItems(large,window);
assert.ok(shown.length<300,`${shown.length} visible objects`);
assert.equal(large.items.filter(n=>n.type==='node').length,2000);
assert.equal(large.items.filter(n=>n.type==='junction'||n.type==='wire').length,0);
assert.ok(visibleItems(large,{...window,y:large.height-500}).some(n=>n.type==='node'));
const related=layoutScene(diagramScene({query:{kind:'and',items:[atom('a','X'),atom('unrelated','U'),atom('b','X')]}},['query']));
const nodes=related.items.filter(n=>n.type==='node');
assert.ok(Math.abs(nodes.find(n=>n.relation==='a').x-nodes.find(n=>n.relation==='b').x)<Math.abs(nodes.find(n=>n.relation==='a').x-nodes.find(n=>n.relation==='unrelated').x));
console.log('Whole rules, nested connections, ordered ports, connectivity layout, source edits and viewport culling passed.');
